### ISSUE TITLE
Add better output when package is ignored

### ISSUE THREAD

**Issue by rmarquis** [falconindy/auracle#10]
For initial context: the package `aurutils` is not installed on my system, but present in my `IgnorePkg` directive.

```
IgnorePkg = aurutils
```

Let's check `aurutils`.
```
$ auracle buildorder aurutils
(no result)
$ auracle download aurutils
(no result)
```

Exit code is 1. It took me a while to understand the issue happens because of the package presence in `IgnorePkg`, so I'd suggest a better output when a package is ignored.

**Comment by falconindy** [comment]
No longer relevant with IgnorePkg support removed.
