### ISSUE TITLE
error: UNKNOWN: Failed sending HTTP request

### ISSUE THREAD

**Issue by henkmet** [falconindy/auracle#102]
I suddenly started getting the error as in the title yesterday (17 May 2023). Therror occurs when running `auracle update`

I rebuilt the auracle-git package but that makes no difference. I'm not sure how to verify that auracle is to blame other than saying that everything else seems to be working fine. Specifically, of auracle's dependencies, I notice curl was updated at that time (17 May 2023). curl on its own works fine though.

**Comment by inglor** [comment]
This is due to https://github.com/curl/curl/issues/11138 scheduled probably for next week patch of curl's official release.

**Comment by misterhsp** [comment]
Have the same problem, downgrade curl helps.

...

**Comment by misterhsp** [comment]
Is this project still alive, the last update was Sep 5, 2020 ?

...

**Comment by putridpete** [comment]
The curl package on Arch was updated not long ago to incorporate some upstream changes, and this seems to have fixed the issue for me with auracle.
