### ISSUE TITLE
`auracle outdated` hangs (forever)

### ISSUE THREAD

**Issue by JAicewizard** [falconindy/auracle#104]
I noticed that `auracle update` currently hangs forever, sometimes.
This seems to be a racerondition, either in auracle or maybe in curl. The finalisation function doesn't seem to be called for the final response, leaving the response unhandled and in the queue forever. In the end the main thread just spins waiting in `Wait`.

I have not tried downgrading curl, and have not used auracle in a couple weeks.
curl (and pacman) versions:
```
# pacman -Q curl pacman
curl 8.7.1-5
pacman 6.1.0-3
```

**Comment by falconindy** [comment]
Surely a race condition, but odd that you're the only person to report this. Years ago I addressed what I thought was the last problem with the event dispatch logic...

Needs better debugging in the library code.

**Comment by dkadioglu** [comment]
I have the same issue since at least last year. Fully updated Arch Linux and AUR build of most recent commit.

**Comment by JAicewizard** [comment]
Yeah this seems really odd, it also happens very consistently for me on my laptop, I almost never get proper results. I started some debugging work at some point, but I quit for some reason, I could not really pinpoint anything.

**Comment by falconindy** [comment]
"outdated" is just some local iterating through pacman DBs, a single HTTP request, and some post-processing. If you're affected by this, could you post the output of `pacman -Qm`? Also, I'd be interested to know if `auracle info $(pacman -Qqm)` hangs in the same way as `auracle outdated`. Perhaps this isn't a problem of the event loop, but some infinite loop in package iteration.

Ideally: build auracle with debug symbols, run it under gdb, and interrupt it while it's hanging to get a backtrace.

**Comment by falconindy** [comment]
Alright, I think I found the bug, and basically it's a repeat of something I fixed 6 years ago and then reintroduced: fdb62c1b04c1d5b7cc4baebb3d99f0cd3cd60c62 (broken in 4259918f). Pushing this blocked behind some other work I've been doing, but I'll get this out soon.

**Comment by falconindy** [comment]
Please reopen this if it's still broken at head.

**Comment by JAicewizard** [comment]
Thanks a lot for looking into this! Really appreciated. I will test it soon and see if it works. I hadn't had time yet to do try to get a backtrace, been really busy sadly

**Comment by JAicewizard** [comment]
works:) Once again, many thanks

**Comment by dkadioglu** [comment]
> works:) Once again, many thanks

Works also for me, trying this since last week and no more hangs. Thank you very much!
