### ISSUE TITLE
Buildorder fails for r-grain

### ISSUE THREAD

**Issue by JAicewizard** [falconindy/auracle#107]
running `auracle buildorder r-grain` gives the following output: `error: INVALID_ARGUMENT: No request type/data specified.`

This is error is very similar to #106, but not fixed by that PR. I tried using that branch, and a fresh `auracle-git` compile from the AUR, to confirm it is indeed not fixed by that.

I currently do not have time to debug this ATM, many PRs that need to be merged and reviews to be done, hence I opened this issue instead of another PR.

**Comment by falconindy** [comment]
I've got a fix, just trying to come up with a test that doesn't involve adding a brazillion packages...

**Comment by JAicewizard** [comment]
Yup, very nice :) it works!
