### ISSUE TITLE
Add --ignorerepo option

### ISSUE THREAD

**Issue by WorMzy** [falconindy/auracle#12]
Would you be interested in implementing the option to ignore repository results when downloading, like cower currently has? It currently doesn't seem to be possible to download snapshots of packages in the AUR if there is a package of the same name in a custom repository.

```
$ auracle search --quiet openxcom                                                                           
openxcom
[...]
$ auracle download openxcom
openxcom is available in myrepo
$ echo $?
1
```

**Comment by AladW** [comment]
https://github.com/falconindy/auracle/issues/6

**Comment by colinkeenan** [comment]
I also need this to be able to replace cower with auracle. I'm confused about the relationship between this and #6.

**Comment by AladW** [comment]
I made a mistake, it should be #4.

**Comment by lisuml** [comment]
Bump.

**Comment by misterhsp** [comment]
Without --ignorerepo option is for me a switch to auracle senseless.

...

**Comment by falconindy** [comment]
What y'all want isn't an --ignorerepo option, you just want the AUR to take precedence over the binary repos. I hear you. I get it.

This wasn't "possible" with cower because it would have been too damn slow. I think auracle is fast enough to make this happen.

**Comment by falconindy** [comment]
Someone who cares about this, please try the "pony" branch. If it doesn't meet your needs, I'd love to understand why it doesn't.

**Comment by WorMzy** [comment]
Thanks for the update! I can't speak for the others, but unfortunately, it doesn't scratch my itch.

I have a local repo which contains AUR packages. If the package updates on the AUR, then 'auracle sync' doesn't detect it, because it's not "foreign". cower's --ignorerepo switch which allowed me to treat my custom repo packages as foreign. e.g. 'palemoon' is in my repo, and in the AUR, if I have an older version installed than is available in the AUR, cower can report that to me, auracle can't:

```
$ cower -u --ignorerepo=wormzy
:: palemoon 28.4.0-1 -> 28.4.1-1
:: softmaker-office-2018-bin 2018.940-1 -> 2018.960-1
```
auracle reports:
```
$ auracle sync
softmaker-office-2018-bin 2018.940-1 -> 2018.960-1
```

If I comment out the wormzy repo in my pacman.conf, auracle can report the version difference:
```
$ auracle sync
palemoon 28.4.0-1 -> 28.4.1-1
softmaker-office-2018-bin 2018.940-1 -> 2018.960-1
```

**Comment by falconindy** [comment]
Thanks WorMzy. I think we can avoid this, too. Could you test again with the next commit (a231a7c)?

**Comment by WorMzy** [comment]
From my perspective, that seems perfect: 
```
$ auracle sync
softmaker-office-2018-bin 2018.940-1 -> 2018.960-1
palemoon 28.4.0-1 -> 28.4.1-1
```
Thanks!

**Comment by misterhsp** [comment]
wow, that was fast. I can test it only tomorrow

**Comment by misterhsp** [comment]
If I reinstall the AUR from the AUR, is it already included or does it still have to be updated?

Thank you...
