### ISSUE TITLE
Missing config

### ISSUE THREAD

**Issue by ILMostro** [falconindy/auracle#14]
Missing configuration options to `auracle`.  Specifically, it would be useful to have the "TargetDir" and "Color" options customizable, as in `cower`.  Currently, `auracle` downloads the package to the directory from whence the tool is called, with no way to specify a target directory.

**Comment by falconindy** [comment]
It's an explicit goal not to have a config file for auracle. I'm going to hold out as long as I can before adding this.

**Comment by ILMostro** [comment]
I'm not sure if this has always been the case, but I see the `-C` option available now to `auracle`.  This can be used to achieve the intended behavior until/unless the configuration file is supported.

**Comment by ILMostro** [comment]
I'm not sure if this has always been the case, but I see the `-C` option available now to `auracle`.  This can be used to achieve the intended behavior until/unless the configuration file is supported.

UPDATE:
Actually, as far as I can tell, this has been added recently by @falconindy.  Around the time of their last comment here.  The diff is visible at https://github.com/falconindy/auracle/commit/35006723d1216fad0f9de9fa87927a22b6232ae3

**Comment by ILMostro** [comment]
So, it seems that there are two issues mentioned in this bug-report.  One, the lack of a configuration file for `auracle`.  The other issue, which has been resolved by the aforementioned commit, was the missing option to `auracle` to change directory before downloading.

**Comment by phcerdan** [comment]
Just in case it helps anyone transitioning from cower to auracle:
create a file `~/.functions`, and in your `.bashrc/zshrc` source it with `source $HOME/.functions`
```bash
cower() {
    auracle -C ~/AUR "$@"
}
```
That will download all the packages in ~/AUR folder when using `cower download xxx`
