### ISSUE TITLE
IgnorePkg in pacman.conf not honoured

### ISSUE THREAD

**Issue by Crouze** [falconindy/auracle#19]
Hi,

I'm not a novice, but this got me stumped. For some reason Auracle does not honour the IgnorePkg entries in /etc/pacman.conf on all of my Arch installs. At first I thought this was typical of the qtpad-git AUR package, but it seems to apply to all AUR packages.

/etc/pacman.conf contains:
`IgnorePkg = qtpad-git rar` 

But _auracle sync_ still results:
`qtpad-git r190.108b09c-1 -> 0-1`
`rar 5.6.0-1 -> 5.6.1-1`

I tried adding and removing packages on the IgnorePkg line, but the result is always the same. Am I missing something, or is this some kind of bug? Auracle build on my systems without issues with all dependencies met. What can I do to further debug?

OS: Arch x64 (latest)
Auracle: airacle-git r47.5eef47b-1

Thanks,
Marco

**Comment by falconindy** [comment]
> I'm not a novice, but this got me stumped.

Then you didn't read the code. In the same way that `pacman -Qu` doesn't care about IgnorePkg, sync doesn't care about IgnorePkgs either. b7f1eeb8a8d24 makes this more apparent.
