### ISSUE TITLE
How to update all AUR installed packages

### ISSUE THREAD

**Issue by dramm33** [falconindy/auracle#24]
Just switched from cower.
For updating packages in cower I used `cower -uddf`.

I see that `auracle sync` is equivalent to `cower -u`, however how do I send that as an argument to `auracle clone` or `auracle download`?

**Comment by bradford-smith94** [comment]
I've been using `auracle download -r $(auracle sync | cut -d ' ' -f 1)`.

**Comment by falconindy** [comment]
You can use `--quiet` or `-q` to get more concise output from `sync`, but otherwise yes, there's no way to do this directly. Note that you can also use `clone` instead of `download` and auracle is smart enough to do fastforward-only updates to existing repos.

**Comment by dylnmc** [comment]
Please make simple addition:

`auracle update` = `auracle download -r \`auracle sync -q\``

This was the great thing about cower. Sure internals are important but how people interact with your software is equally as important. This should have first class support. *Why is it not already first class*?
