### ISSUE TITLE
Compiling from AUR or source fails

### ISSUE THREAD

**Issue by wyjek** [falconindy/auracle#25]
Hi,
I'm trying to compile auracle, but it fails and I don't know what the problem is. Here's the output I get:
```
ninja: Entering directory `build'
[1/20] Compiling C++ object 'libaur@sta/src_aur_aur.cc.o'.
FAILED: libaur@sta/src_aur_aur.cc.o 
c++ -Ilibaur@sta -I. -I.. -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O0 -g -include config.h -fPIC  -MD -MQ 'libaur@sta/src_aur_aur.cc.o' -MF 'libaur@sta/src_aur_aur.cc.o.d' -o 'libaur@sta/src_aur_aur.cc.o' -c ../src/aur/aur.cc
../src/aur/aur.cc:8:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
[2/20] Compiling C++ object 'libaur@sta/src_aur_request.cc.o'.
ninja: build stopped: subcommand failed.
```

**Comment by falconindy** [comment]
filesystem is a standard header which is part of c++17. I don't know what you've done here for the build to find the linkable object but the header not be available. Not really an auracle problem, though.

**Comment by falconindy** [comment]
Could you please clarify what distro you're building this from? Is it a legit Arch install? The filesystem header should be `/usr/include/c++/8.2.1/filesystem` provided by the gcc package in core (regardless of whether you compile with gcc or clang).
