### ISSUE TITLE
[Q] Custom output 's colors

### ISSUE THREAD

**Issue by tuyenpm9** [falconindy/auracle#26]
Currently we only have auto/never/always, how about allow user to custom the output's colors like: color `aur`, `package-name`, `package-version`, `package-version flagged as out-of-date`, `description`.

**Comment by falconindy** [comment]
See f615a22be85c7b2564687492f744456a2430fc90 on the "formatting" branch.

**Comment by tuyenpm9** [comment]
Is there any difficulty that it's not in master?

**Comment by falconindy** [comment]
Sure, I'm not 100% happy with the code yet and I'm on vacation for another week.

**Comment by tuyenpm9** [comment]
Okay, we'll wait :)

have great vacation.
