### ISSUE TITLE
[Q] Howto update installed packages

### ISSUE THREAD

**Issue by tuyenpm9** [falconindy/auracle#27]
`cower` has `-u` to check for newly version of installed packages, how would `auracle` come to packages that downloaded via `download` and `clone`?

I think this feature is really useful.

**Comment by falconindy** [comment]
See #24. There's no first class support for this right now.

**Comment by tuyenpm9** [comment]
Sorry my question is not clear enough, I've just want to check the new version of pacakges that **downloaded or cloned** using auracle, does that `sync` do this task? Because I see from `--help` that cower also only check for new version against AUR. @falconindy

**Comment by falconindy** [comment]
`sync` only compares versions in the AUR to the local pacman DB, so it's very much like `cower -u`. I currently have no plans to extend this.

**Comment by tuyenpm9** [comment]
Yep, I just need to compare version only, build & install manually.

**Comment by scottgigante** [comment]
In case anyone lands here looking for an answer, it's `auracle download -r $(auracle sync -q)`.

**Comment by Wunkolo** [comment]
> In case anyone lands here looking for an answer, it's `auracle download -r $(auracle sync -q)`.

Is this going to keep being the top result on google for `auracle update` that I'm going to always have to search for to get this command again or is this planned to be a built-in feature at some point.
