### ISSUE TITLE
buildorder with multiple packages hangs forever

### ISSUE THREAD

**Issue by vivien** [falconindy/auracle#28]
_EDIT: This issue was initially a suggestion to merge the clone and download options which isn't legit in the end, but pointed out an issue with buildorder, see point 4. in comments._

Hi! Thanks for the tool. I find it somehow frustrating to fetch packages in the current directory instead of a dedicated cache. Also, the "clone" and "download" options seem a bit redundant to me. We could also mention the behavior we get when issuing a clone after a download:

````
$ auracle download auracle-git 
download complete: /home/vivien/tmp/auracle-git
$ auracle clone auracle-git 
fatal: destination path 'auracle-git' already exists and is not an empty directory.
error: clone failed for auracle-git: git exited with unexpected exit status 128
````

"clone" already abstract "clone or update", thus I imagine a "fetch" command shadowing (ideally replacing) both "clone" and "download" commands in a standard dedicated auracle cache directory. The wrapper below makes it easier to understand the requested behavior:

```` sh
#!/bin/sh

set -e

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
AURACLE_HOME="$XDG_CACHE_HOME/auracle"
AURACLE_BIN=/usr/bin/auracle

mkdir -p "$AURACLE_HOME"
cd "$AURACLE_HOME"

if [ "$1" = "fetch" ]
then
  shift
  exec $AURACLE_BIN clone "$@"
else
  exec $AURACLE_BIN "$@"
fi
````

The rationale behind this is that auracle is intended to be a simple tool, thus combining two fetching options into one seems appropriate.

Also, AUR package clones or downloaded archives are often temporary in one's workflow. Thus defaulting to using a cache directory would prevent the user from changing working directory before or deleting the package directory after invoking auracle, making its usage even more smooth.

If downloading/cloning a package in a specific directory (e.g. the current one) is needed, auracle could still provide a switch to override the cache directory or use `-C`.

**Comment by vivien** [comment]
Hum, while "clone" and "download" still seem redundant, managing a cache directory might be out-of-scope for auracle, especially since a wrapper script to fetch/install/update is not that complicated to write. I'm closing this.

**Comment by falconindy** [comment]
Thanks for the report. I get that download and clone are slightly redundant, but I'm trying to avoid too much abstraction in auracle and rather just expose AUR functionality in a handy commandline package. I'd like to crowd source new features by way of finding out the common things people are doing with auracle in scripts, and where they're struggling to achieve what they need. Also, because I'm the author, you should expect to see things that might violate these principles, because they suit my own needs :smile:.

**Comment by vivien** [comment]
And this is what I like about *auracle*, it's a simple tool without configuration file which simply downloads AUR packages but does not step on makepkg nor pacman feet.

Below is the content of my final `aur` script, which caches and installs given AUR packages (and their dependencies) with `aur <pkg>`, or update out-of-date AUR packages if no argument is provided with `aur`.

```` sh
#!/bin/sh

set -e

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/aur"

mkdir -p "$CACHE"

[ $# -gt 0 ] || set -- $(auracle --quiet sync)

for pkg in "$@"
do
  pushd "$CACHE"
  for dep in $(auracle buildorder "$pkg" | awk '{ print $2 }')
  do
    auracle clone "$dep"
    pushd "$dep"
    makepkg -si
    popd
  done
  popd
done
````

A few notes though:

1) `nlohmann-json` makes it tricky to bootstrap *auracle*. But since it's a one-time thing (it can upgrade itself afterwards), it'd be great to have at least bootstrap commands / first steps in the project README.

2) if `--quiet` worked with *buildorder*, I could avoid the `awk` filter which gets rid of the `BUILD` keyword.

3) `auracle buildorder clight-git clightd-git` hangs forever. If multiple packages worked with *buildorder* I could remove one for-loop and directly use `for pkg in $(auracle buildorder "$@")`!

4) it seems like auracle is querying the installed package which results in a different output for e.g. *auracle buildorder clight-git* once the package is installed. It's a good default behavior but it'd be great to have a switch to disable the local query for inspection.

Thank you!

**Comment by falconindy** [comment]
Thanks. Sounds like there's at least one bug report hidden in here. Let me reply to each of your points:

1. What about this bootstrap is difficult? Is it just the size of the download? Just the fact that it's an AUR dep? I'm definitely sensitive to this.

2. Point taken, but consider that in the future, there might be verbs other than just `BUILD`.

3. I can't reproduce this, and it's not clear to me from the dependencies why this might loop forever.

```
$ auracle buildorder clight-git clightd-git                                                                                                                                                                      
BUILD ddcutil
BUILD libmodule
BUILD clightd-git
BUILD clight-git
```

There used to be problems with dep loops (see #7), but that's long since fixed. Would you be able to build auracle with debug symbols, run it under gdb, and get a backtrace while it's hanging? This is definitely a bug.

4. Yes, that seems working as intended. Could you expand on why you need the buildorder output to include dependencies which are already satisfied? Would this be bounded at the dependency leaf or recurse into the buildorder of the met dependencies as well? I suppose these could be output with some sort of DEPMET prefix but it's not immediately obvious to me why this is wanted or what the behavior should be (and rationale for why it behaves that way).

Thanks for your feedback!

**Comment by vivien** [comment]
Sorry if I was unclear.

1. I meant that the very least I can think of (because thanksfully *nlohmann-json* and *auracle-git* only have a PKGBUILD file) to install auracle on a system is this:
```` sh
for p in nlohmann-json auracle-git
do
  mkdir /tmp/$p
  pushd /tmp/$p
  curl "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$p" > PKGBUILD
  makepkg -si
  popd
done
````
Installing two packages like this by hand might be reluctant to some in order to try well... an AUR helper. Writing something like that in the README could help, but it's just my opinion ;-)

2. Ho ok, what other verbs can come here? As I wanted to list which package needed to be installed, I though `--quiet` would be a legit option to restrict the output to package names only. I didn't think further than that.

3. Here's what I get: http://ix.io/1s4Y (same problem.)

4. The rationale behind this was that auracle is meant to be used as a tool to wrap higher level commands such as install or update. Writing such programs would require some testing and inspection, so I thought about an option which would make auracle run *buildorder* as if the target packages weren't installed, instead of removing them before testing again. But hey, once the wrapper is written, there might be no reason to have this option... The other reason I can think of is if you want to list a package and its dependencies (from AUR, regardless the local system). This would be hard to inspect once the package is installed. But maybe I'm lacking some pacman-fu here, I'm not even sure how to do that for normal packages.

**Comment by falconindy** [comment]
Odd, I think the backtrace indicates that the hang is somewhere in the event loop accounting. Could you run auracle with AURACLE_DEBUG=1 in the environment and post that output?

Also of interest: do you see similar hangs with build/clone on those two packages when done recursively? Non-recursively? What packages from the dep chains do you already have installed?

**Comment by vivien** [comment]
For those tests I just uninstalled `clightd-git` and `clight-git`. I kept their dependencies installed:

````
$ AURACLE_DEBUG=1 ./build/auracle buildorder clight-git clightd-git
*   Trying 5.9.250.164...
* TCP_NODELAY set
* Connected to aur.archlinux.org (5.9.250.164) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=aur.archlinux.org
*  start date: Nov  6 23:00:52 2018 GMT
*  expire date: Feb  4 23:00:52 2019 GMT
*  subjectAltName: host "aur.archlinux.org" matched cert's "aur.archlinux.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x561c7aeb3140)
> GET /rpc?v=5&type=info&arg[]=clight-git&arg[]=clightd-git HTTP/2
Host: aur.archlinux.org
User-Agent: Auracle/0
Accept: */*
Accept-Encoding: deflate, gzip

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx/1.14.0
< date: Fri, 16 Nov 2018 21:31:07 GMT
< content-type: application/json
< expires: Tue, 11 Oct 1988 22:00:00 GMT
< x-frame-options: DENY
< cache-control: public, must-revalidate, max-age=0
< etag: W/"6c08fe321247ab1c1dd6f947ea7035a9"
< x-cache: BYPASS
< content-encoding: gzip
< 
* Connection #0 to host aur.archlinux.org left intact
* Found bundle for host aur.archlinux.org: 0x561c7aea54f0 [can multiplex]
* Re-using existing connection! (#0) with host aur.archlinux.org
* Connected to aur.archlinux.org (5.9.250.164) port 443 (#0)
* Using Stream ID: 3 (easy handle 0x561c7c293640)
> GET /rpc?v=5&type=info&arg[]=clightd-git HTTP/2
Host: aur.archlinux.org
User-Agent: Auracle/0
Accept: */*
Accept-Encoding: deflate, gzip

* Found bundle for host aur.archlinux.org: 0x561c7aea54f0 [can multiplex]
* Conn: 0 (0x561c7aea49c0) Receive pipe weight: (-1/0), penalized: FALSE
* Multiplexed connection found!
* Found connection 0, with requests in the pipe (1)
* Re-using existing connection! (#0) with host aur.archlinux.org
* Using Stream ID: 5 (easy handle 0x561c7c294e80)
> GET /rpc?v=5&type=info&arg[]=ddcutil&arg[]=libmodule HTTP/2
Host: aur.archlinux.org
User-Agent: Auracle/0
Accept: */*
Accept-Encoding: deflate, gzip

< HTTP/2 200 
< server: nginx/1.14.0
< date: Fri, 16 Nov 2018 21:31:08 GMT
< content-type: application/json
< expires: Tue, 11 Oct 1988 22:00:00 GMT
< x-frame-options: DENY
< cache-control: public, must-revalidate, max-age=0
< etag: W/"1075ce3e02aab4aad1d52a69cd28a714"
< x-cache: BYPASS
< content-encoding: gzip
< 
< HTTP/2 200 
< server: nginx/1.14.0
< date: Fri, 16 Nov 2018 21:31:08 GMT
< content-type: application/json
< expires: Tue, 11 Oct 1988 22:00:00 GMT
< x-frame-options: DENY
< cache-control: public, must-revalidate, max-age=0
< etag: W/"b42c33a22ecb651c83f0cd2420f7bd06"
< x-cache: BYPASS
< content-encoding: gzip
< 
* Connection #0 to host aur.archlinux.org left intact

^C
````

Yes, `clone --recurse` hangs forever as well on *update*:
````
~/.cache/aur $ rm -rf clightd-git/ clight-git/
~/.cache/aur $ ~/src/auracle/build/auracle --recurse clone clight-git clightd-git
update complete: /home/vivien/.cache/aur/libmodule
clone complete: /home/vivien/.cache/aur/clight-git
clone complete: /home/vivien/.cache/aur/clightd-git
update complete: /home/vivien/.cache/aur/ddcutil
~/.cache/aur $ ~/src/auracle/build/auracle --recurse clone clight-git clightd-git
update complete: /home/vivien/.cache/aur/clight-git
update complete: /home/vivien/.cache/aur/clightd-git

^C
````


But `~/src/auracle/build/auracle buildorder clightd-git clight-git` hangs with them installed as well.

**Comment by falconindy** [comment]
Thanks. Might take me a few days to get to this, but I should have enough info here to reproduce the bug on my own.

**Comment by vivien** [comment]
Thank you. For point 4, once issue I have is the update of -git AUR package. I need to force the listing of a -git package as well as its -git dependencies so that I can run `makepkg` for them again, and eventually pull updates. For example, clight-git depends on clightd-git. I can imagine a `--nosync` option for buildorder which may help me do this. But that might not the be cleanest way. Can auracle detect such packages with a rolling (non-release) source maybe?

**Comment by falconindy** [comment]
If you have an installed package and want to know its deps recursively, pactree from (community/pacman-contrib) can do this for you (in both human and machine readable formats). I agree that it might be nice to have that natively in auracle. Feel free to open a separate feature request for this and I'll triage as I have time.

I'm having problems reliably reproducing the hang you've described. It seems to be a race condition where a request callback is never called (and thus the event loop never terminates). I hypothesized that it was due to a "slow" remote while recursing through package dependencies, but I can't replicate that locally with my test harness (via injecting delay into server responses). Frustrating. Will keep poking at this.

**Comment by falconindy** [comment]
Found it. Seems to be a bad assumption I made in 11498adc about requests never finishing concurrently. This should be fixed in fdb62c1b04c1d5b7cc4baebb3d99f0cd3cd60c62.

**Comment by vivien** [comment]
This is fixed! Hence here's my updated `aur` script with latest auracle:

```` sh
#!/bin/sh

set -e

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/aur"

mkdir -p "$CACHE"

[ $# -gt 0 ] || set -- $(auracle --quiet sync)

pushd "$CACHE"

for pkg in $(auracle buildorder "$@" | awk '{ print $2 }')
do
  auracle clone "$pkg"
  pushd "$pkg"
  makepkg -si
  popd
done

popd
````

Thank you!

**Comment by falconindy** [comment]
Thanks, I would still encourage you to pay attention to the first column of the buildorder output. With fdb62c1b04c1d5b7cc4baebb3d99f0cd3cd60c62, I'm setting the stage for extending this and having identifiers other than just BUILD (currently thinking of at least UNKNOWN when a package cannot be resolved at all, and maybe LOCAL for already satisfied deps). You could do something like:

```sh
while read -r id dep _; do
  case $id in
    BUILD)
      ( auracle clone "$dep" && cd "$dep" && makepkg -si )
      ;;
    *)
      echo "unhandled action $id for $dep"
      ;;
  esac
done < <(auracle buildorder "$@")
```

But then I also have to point out that the directory name of the clone is the pkgbase, not the package name. Perhaps I should amend the buildorder output to be "ID PKGNAME PKGBASE".
