### ISSUE TITLE
List dependencies recursively without syncing

### ISSUE THREAD

**Issue by vivien** [falconindy/auracle#29]
In order to rebuild/reinstall non-release packages (usually -git packages), we'd need to list all of their dependencies without syncing with the local system, because a -git package might depend on another, e.g. `clight-git` depends on `clightd-git` or `sway-git` depends on `wlroots-git` and more.

The trick would be to define if a package is installed or not and eventually play with pactree, while we could imagine a `--nosync` option for example to use with `auracle buildorder`.

**Comment by falconindy** [comment]
Could you take a look at the extended-buildorder branch? eec99441bb2ce443d34cc3f0f017c334925a97f2 should provide what you need, albeit by taking a different approach.

**Comment by vivien** [comment]
I tried the branch, this might help but what remains tricky is to differ which packages are AUR or not from that list:

````
$ ./build/auracle buildorder clight-git
SATISFIED systemd
SATISFIED popt
SATISFIED libconfig
SATISFIED gsl
SATISFIED linux-api-headers
SATISFIED libx11
SATISFIED libxrandr
SATISFIED libxext
SATISFIED polkit
SATISFIED libxss
SATISFIED glib2
SATISFIED libusb
SATISFIED udev
SATISFIED libdrm
SATISFIED ddcutil
SATISFIED git
SATISFIED cmake
SATISFIED libmodule
SATISFIED clightd-git
SATISFIED clight-git
````

Standard packages will be handled by `makepkg -s`, that they aren't useful to me in this list. My use case is still to rebuild the fetch/installation of a package such as `sway-git` or `clight-git`, as well as their dependencies.

Ideally non-release packages only, but that isn't a big deal to reinstall all of them. Although it seems like these packages can be identified by their source value being *SKIP*.

**Comment by falconindy** [comment]
So essentially, you'd want to replace `SATISFIED` with either `BUILD` or `INSTALL`.

**Comment by falconindy** [comment]
No, that's out of scope for Auracle. It's also a bad heuristic. For example, gpg keys will have a checksum of SKIP.

**Comment by vivien** [comment]
I understand. So at least I'd need to differ an AUR package from a standard
one, so that I can run `makepkg` on them.

**Comment by falconindy** [comment]
Eh, right. Ok... so what if the output was a little more nuanced and indicated both -- the provenance as well as whether or not it was satisfied. For example:

```
$ auracle buildorder clight-git
SATISFIEDBINARY systemd
SATISFIEDBINARY popt
BINARY libconfig
BINARY gsl
SATISFIEDBINARY linux-api-headers
SATISFIEDBINARY libx11
SATISFIEDBINARY libxrandr
SATISFIEDBINARY libxext
SATISFIEDBINARY polkit
SATISFIEDBINARY libxss
SATISFIEDBINARY glib2
SATISFIEDBINARY libusb
SATISFIEDBINARY udev
SATISFIEDBINARY libdrm
FOREIGN ddcutil
SATISFIEDBINARY git
SATISFIEDBINARY cmake
SATISFIEDFOREIGN libmodule
FOREIGN clightd-git
FOREIGN clight-git
```

**Comment by vivien** [comment]
This output is a bit heavy but you know the package vocabulary more than anyone else, as long as I can grep an AUR specific keyword (here `FOREIGN`) this will solve my use case!

(This makes me think about the `--porcelain` output of git status btw.)

Regarding the non-release packages, I understand this is out-of-scope for Auracle. However can I ask you how you would reliably extract this info? I wouldn't mind piping a filter script to `auracle pkgbuild <pkg>` to cherry pick these specific foreign packages, but I'm not sure what to look for.

**Comment by falconindy** [comment]
I'm not really sure it's "heavy". What I'm finding is that it's really just necessary. The current output is entirely insufficient. It's not informative enough, as you've already found.

I was actually thinking of expanding it even further to include a second column that denotes the type of dependency -- depends, makedepends, checkdepends. This would allow some wrapper script to build everything while skipping checkdepends, for example. Ideally, you'd want to parse this in tabular format, like I suggested in the other issue:

```sh
while read -ra avail deptype pkgname pkgbase; do
  case $avail in
    FOREIGN*)
      ( auracle clone "$pkgname" && cd "$pkgbase" && makepkg )
      ;;
  esac
done < <(auracle buildorder ...)
```

> Regarding the non-release packages, I understand this is out-of-scope for Auracle. However can I ask you how you would reliably extract this info?

If you wanted something parseable, I think you'd want to fetch the .SRCINFO, not the PKGBUILD. You could look for VCS sources, and that would likely only net you some false negatives (where they pin to a specific commit or tag).

**Comment by vivien** [comment]
I'm fine with whatever formatting you end up choosing as long as I can distinguish the foreign packages ;-)

> > Regarding the non-release packages, I understand this is out-of-scope for Auracle. However can I ask you how you would reliably extract this info?
>
> If you wanted something parseable, I think you'd want to fetch the .SRCINFO, not the PKGBUILD. You could look for VCS sources, and that would likely only net you some false negatives (where they pin to a specific commit or tag).

Pining to a specific commit or tag wouldn't be a problem I guess because it won't modify the PKGBUILD and is deterministic. What sucks here is determining if the package is designed to pull arbitrary updates from the VCS sources or not...

**Comment by falconindy** [comment]
Yes, and much of that isn't for auracle to decide. We need better support in PKGBUILD itself or, more likely, additional metadata in the AUR.

**Comment by E5ten** [comment]
If it's still being considered I'd find an extra column indicating dependency type (like {,make,check} I mean) to be a useful addition.

**Comment by falconindy** [comment]
This is nontrivial and can't just be added as another column. In order for that to be useful, you have to know the hierarchy. For example, what if a checkdepend has further dependencies. Are those checkdepends as well? What if one of those deps is later found to be a makedepend or depend?

**Comment by E5ten** [comment]
That's a good point, it didn't occur to me the complexity of that. Maybe instead of that there could be a flag to disable checkdepends? So the checkdepends aren't added in the first place and therefore those further dependencies of each checkdepend aren't either?

**Comment by falconindy** [comment]
Closing this since it's large solved by the newer buildorder output. Filtering of checkdepends can currently be done at the wrapping script level with an extra RPC call and use of the -F switch.
