### ISSUE TITLE
makepkg modifies PKGBUILD and breaks auracle clone

### ISSUE THREAD

**Issue by vivien** [falconindy/auracle#31]
I'm using this script at the moment which only uses the `clone` command to update AUR packages:

```` sh
#!/bin/bash

set -e

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/aur"

mkdir -p "$CACHE"

[ $# -gt 0 ] || set -- $(auracle --quiet sync)

while read -r id dep _
do
  pushd "$CACHE"
  case $id in
   BUILD)
     auracle clone "$dep"
     pushd "$dep"
     makepkg -si
     popd
     ;;
   *)
     echo "Unhandled action $id for $dep"
     ;;
  esac
  popd
done < <(auracle buildorder "$@")
````

and all repos in the cache directory end up eventually with an unmodified PKGBUILD file: http://ix.io/1uiZ
I am not sure yet which sequence leaves these repositories dirty.

(N.B.: it'd be great if AUR repositories had a `.gitignore` file excluding `pkg/`, `src/` and `*.tar.xz`.)

**Comment by vivien** [comment]
It looks like `makepkg -si` is modifying `pkgver` in the PKGBUILD file when updating the repo.

**Comment by falconindy** [comment]
Yes, makepkg can and will do this. I'm not clear on what the problem being reported is.

**Comment by vivien** [comment]
Well `auracle clone` actually clones a repository or pulls it if it is already cloned. But problem is that one will usually use `makepkg` in conjunction with `auracle` and thus end-up with a dirty repo that Auracle won't update.

Hence you'll have to do something like this:

```` sh
...
  BUILD)
    [ -d "$dep" ] && git -C "$dep" reset --hard HEAD
    auracle clone "$dep"
    pushd "$dep"
    makepkg -si
    popd
    ;;
...
````

which defeats the purpose of using `auracle clone` to update a repo.

Would the best practice be to run `git reset --hard HEAD` after `makepkg -si`?

**Comment by Morganamilo** [comment]
As i hinted at in #47 the solution is to run `git reset --hard HEAD` before pulling.

**Comment by falconindy** [comment]
Rather than throwing away changes, it seems git will let you autostash on a pull+rebase. Seems substantially better for people maintaining local changes. I strongly dislike the idea that an update would forcibly discard a user's changes. That's surprising behavior, and downright mean.

Would be very interested to know how this new behavior breaks.

**Comment by Morganamilo** [comment]
I strongly believe people maintaining local changes should commit them. Resetting to HEAD will not erase them and `git pull [--rebase]` will merge the local changes automatically.

**Comment by falconindy** [comment]
Well, that's exactly what the new functionality does, but it also accounts for changes that might not be committed, like pkgver bumps from makepkg. Seems like the best of both worlds, no?
