### ISSUE TITLE
Always include target package in buildorder?

### ISSUE THREAD

**Issue by InspectorMustache** [falconindy/auracle#32]
`buildorder` lists all AUR dependencies that aren't already installed on the system. This is also true for the target package specified on the commandline. So `auracle buildorder foo` will only include foo if it's not already installed. But since the point of `buildorder` is to gauge what needs to be done to build the target package, it might make sense to always include it in the buildorder list?

**Comment by falconindy** [comment]
Yes,. I've been rethinking what this output should contain. Roughly, I want to discard the idea that anything is omitted, but rather indicate in the output that the dep is already satisfied.

**Comment by InspectorMustache** [comment]
Yeah, that sounds great. I was actually surprised the local database was queried at all for this command.
