### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by dramm33** [falconindy/auracle#36]
Not sure if it's a bug on my end or if this just isn't implemented yet but completions (pressing tab) don't work at all for me.

Neither for commands (sync, clone, etc) nor for the names of the packages.

I'm using zsh.

**Comment by falconindy** [comment]
Right, there's only bash completion. I'm not a zsh user, so I'm not familiar with writing completion files for zsh. Patches welcome.

**Comment by dramm33** [comment]
I never wrote any code for that either but I will definitely look into it.
I saw that cower had `extra/zsh_completion` so I'll start from there.

**Comment by falconindy** [comment]
Poof, there's ZSH completions now.

**Comment by inglor** [comment]
@lolilolicon How is that completion suppose to work? typing `auracle s<Tab>` does nothing.

**Comment by lolilolicon** [comment]
Well, that sounds pretty rude. As if I would push this without a basic testing. PEBKAC?

**Comment by inglor** [comment]
It was a genuine question, not a doubt in your abilities.

**Comment by lolilolicon** [comment]
Well the question isn't very well formulated.
How is it supposed work? It's just vanilla zsh <Tab> completion.
Did you try a zsh session? Open a new terminal window?
If some bug is discovered, I'd be glad as we'll be improving it.

**Comment by inglor** [comment]
I got it. It was OMZ messing the completion. I followed the instructions and now it works. In case anyone else have issues this [1] and this [2] will help.

[1]: https://github.com/zsh-users/zsh-completions/blob/5bef0323984bbec2def9839fb52db00285a07ebf/README.md#oh-my-zsh
[2]: https://github.com/zsh-users/zsh-completions/issues/603
