### ISSUE TITLE
Handling network issues

### ISSUE THREAD

**Issue by Maximalfr** [falconindy/auracle#37]
If the network is inaccessible or the computer is in airplane mode, auracle is terminated with a nlohmann error.

`terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
[1]    15465 abort (core dumped)  auracle sync`

**Comment by falconindy** [comment]
I agree that it's not a great error message, but the behavior seems fine. There's no real way to recover from this.

**Comment by falconindy** [comment]
Had a chance to experience this while the AUR was down. Should be fixed.
