### ISSUE TITLE
Bad free of curl_easy_escape's return value

### ISSUE THREAD

**Issue by heftig** [falconindy/auracle#39]
Arch Linux curl 7.64.0-6 accidentally enabled memory allocation debugging (`--enable-curldebug`), which exposed a bug in auracle (and cower).

The `free` at [aur/request.cc:16](https://github.com/falconindy/auracle/blob/1c6b5846ab8955dc5244788b8618969ef5ad93b7/src/aur/request.cc#L16) should be a `curl_free` instead.
https://github.com/falconindy/auracle/blob/1c6b5846ab8955dc5244788b8618969ef5ad93b7/src/aur/request.cc#L13-L19

**Comment by falconindy** [comment]
Fixed by #38
