### ISSUE TITLE
Get color default from pacman.conf

### ISSUE THREAD

**Issue by E5ten** [falconindy/auracle#42]
If `Color` is not enabled in pacman.conf it would be nice if auracle displayed colorless output by default as well.

**Comment by falconindy** [comment]
I'm pretty opposed to this idea.

- It's highly surprising that a only a remotely related config file would affect auracle. Yes, I realize IgnorePkg is taken from here, and it's a decision I regret not thinking about more before carrying it over from cower.
- alpm integration is only a minor part of auracle. It never even invokes pacman, only borrowing enabled repos.
- I wouldn't parse /etc/pacman.conf if I could avoid it, but pacman is too dumb to be able to provide an API for parsing/exposing its own config file.

**Comment by E5ten** [comment]
What about being able to set an environmental variable like AURACLE_NOCOLOR to by default not use color?

**Comment by falconindy** [comment]
Let's turn this around -- why is --color=auto an unacceptable default? I tend to think the uncolored output is pretty unreadable. Could we improve the color scheme or what gets colored to make this better for you?

**Comment by E5ten** [comment]
I have no issues with what is coloured/the colour scheme, just don't have colour output in pacman and like consistency, but it isn't really a problem if auto is always default, and it makes sense that you wouldn't want to add pacman.conf parsing or an extra environmental variable.
