### ISSUE TITLE
Missing info output

### ISSUE THREAD

**Issue by rmarquis** [falconindy/auracle#5]
Compared to `cower --info` output, `auracle info` is currently less detailed:

* missing Licenses info
* missing Out of Date status
* for packages that are flagged, missing flagged date string
* for packages that are locally installed but outdated, missing `[installed: oldversion]` string

```
$ cower -ic cower
Repository     : aur
Name           : cower [installed: 17-1]
Version        : 17-2
URL            : http://github.com/falconindy/cower
AUR Page       : https://aur.archlinux.org/packages/cower
Keywords       : aur
Depends On     : curl  pacman  yajl
Makedepends    : perl
License        : MIT
Votes          : 887
Popularity     : 31.11
Out of Date    : No
Maintainer     : falconindy
Submitted      : Thu 30 Dec 2010 03:30:37 CET
Last Modified  : Mon 24 Apr 2017 16:27:21 CEST
Description    : A simple AUR agent with a pretentious name
```

I also just realized this `installed:` string in cower is printed next to the name, it might be more logical to place it next to the current version.

**Comment by falconindy** [comment]
Thanks! In order...

* Missing licenses is a typo -- that's fixed locally.
* Out of Date status is present when a package is out of date.
* See above
* Yes, this is missing. Definitely makes more sense to include this next the version, not the name...
