### ISSUE TITLE
auracle sync has exit code 0 when there are no updates

### ISSUE THREAD

**Issue by E5ten** [falconindy/auracle#50]
I'm not sure if this is the intended behaviour or not but pacman -Qu has exit code 1 if there are no updates so I figured I'd make an issue in case.

**Comment by falconindy** [comment]
Not intended. I've got a patch queued locally with a fix (and test). Thanks!

**Comment by polyzen** [comment]
You may remember the `checkupdates` script from pacman-contrib was recently made to return 1 when no updates are found, [to match `pacman -Qu`](https://bugs.archlinux.org/task/62336), but now a different exit code is being considered as this has lead to the following:
> This complicates creating a systemd timer that runs `checkupdates --download`, since the service would be marked as "failed" if checkupdates doesn't find updates. If checkupdates would return e.g. "2" instead of "1" then It would be possible to use "SuccessExitStatus=" in the unit file.
https://bugs.archlinux.org/task/64219

You may want to consider this for `auracle sync` as well.
