### ISSUE TITLE
Errno 113 : No Route to Host During Install

### ISSUE THREAD

**Issue by nopathrepo** [falconindy/auracle#52]
Terminal output : https://pastebin.com/M98UdZjf 
I can't tell if this is an issue with my system or with connection to auracle itself. I don't have a firewall on my system so I'm not sure why it would be doing this.
System info : https://pastebin.com/BRWjGU2h

**Comment by falconindy** [comment]
Looks like meson fails to download source for the libfmt dep. Up to you to figure out why your internet fails at this point. Alternatively, you can install libfmt prior to building auracle and skip the download. I dont really support shared linking of fmt, though.

**Comment by nopathrepo** [comment]
Installing the fmt package via pacman solved this issue. Thanks for your swift response.

**Comment by stefanhusmann** [comment]
Well, downloading fmt fails for me, too, with the same error messages.

**Comment by ortango** [comment]
stefanhusmann:

i think wrapdb.mesonbuild.com is just down for the time being.
