### ISSUE TITLE
segmentation fault (core dump) 

### ISSUE THREAD

**Issue by tmpm697** [falconindy/auracle#55]
I've got below error with archlinux system up-to-date, I doubt something new kernel or systemd..etc breaks auracle:

```aur search inspect
zsh: segmentation fault (core dumped)  auracle search inspect
```

**Comment by falconindy** [comment]
Works for me. You'll need to provide a symbolized coredump if you want assistance in debugging this.

**Comment by falconindy** [comment]
Please make sure this isn't a dupe of #54.

**Comment by tmpm697** [comment]
curl has been fixed.
