### ISSUE TITLE
Checking and downloading foreign packages

### ISSUE THREAD

**Issue by p1839251** [falconindy/auracle#57]
Hello,
I've been using cower for 4 years now. I'm trying migrating from cower to auracle but there's a feature (cower -du or -ddu) that I really enjoyed and I can't really figure out how to achieve the same results with auracle.
`$auracle sync`  works, but neither `$auracle sync download` nor `$auracle download sync` works as expected.
The only one that has worked so far is `$auracle clone $(auracle sync -q)`, which isn't pretty at all and I assume/hope there's a better way to do it.

**Comment by falconindy** [comment]
See #24 and #27. This doesn't exist right now and I'm not convinced there's a need for it if you're using git repos instead of tarballs.

**Comment by p1839251** [comment]
Thank you for your answer.
Maybe, later on, you'll change your mind as it seems to be a requested feature.
