### ISSUE TITLE
Search returns exit code 0 with no results

### ISSUE THREAD

**Issue by jeffmhubbard** [falconindy/auracle#59]
This is pretty much the same as #50, but with the search command. Search always returns 0, even if there are no results.

**Comment by falconindy** [comment]
No, not at all the same. An exit code of zero means auracle successfully executed the search, but found no results.

**Comment by Morganamilo** [comment]
Pacman exits 1 if there are no results though.

**Comment by jeffmhubbard** [comment]
> No, not at all the same. An exit code of zero means auracle successfully executed the search, but found no results.

I  had considered that might be the case, but...

> Pacman exits 1 if there are no results though.

Both pacman -Ss and -Qs return 1 with no results.

**Comment by falconindy** [comment]
IMO, pacman is wrong.

**Comment by falconindy** [comment]
If you want to convince me to change this, explain how (preferably with code examples) this would improve your life.

**Comment by jeffmhubbard** [comment]
It's not particularly life altering in any way. Some of the commands exit 1 and state "no results found for badpkgname", some don't. If that's intentional, then it's working as expected.
