### ISSUE TITLE
Request: Add 'armv6h' to arch=()

### ISSUE THREAD

**Issue by holgersson32644** [falconindy/auracle#60]
Hi,
please add 'armv6h' for plattforms like the RaspberryPi to your PKGBUILD.
I'm running auracle-git with pacaur for several months on my raspberry pi
and had no issues so far.

I know the PKGBUILD is in a seperate repository, but I think the test.log is better of at github than inside a comment section on the AUR webinterface.

Output of the tests and the generated logfiles follow.

Best regards,
Nils

```
meson test -C build
ninja: Entering directory `/tmp/auracle-git/src/auracle/build'
ninja: no work to do.
 1/15 libaur_request_test                     OK       0.15 s 
 2/15 libaur_response_test                    OK       0.10 s 
 3/15 libauracle_package_cache_test           OK       0.07 s 
 4/15 libauracle_format_test                  OK       0.15 s 
 5/15 libauracle_sort_test                    OK       0.10 s
 6/15 auracle_buildorder_integration_test     OK       5.45 s
 7/15 auracle_clone_integration_test          OK       5.55 s
 8/15 auracle_custom_format_integration_test  OK       4.99 s
 9/15 auracle_info_integration_test           OK       3.93 s
10/15 auracle_raw_query_integration_test      OK       4.63 s
11/15 auracle_regex_search_integration_test   OK       3.93 s
12/15 auracle_search_integration_test         OK       6.20 s
13/15 auracle_show_integration_test           OK       5.55 s
14/15 auracle_sort_integration_test           OK       4.84 s
15/15 auracle_sync_integration_test           OK       3.93 s

Ok:                   15
Expected Fail:         0
Fail:                  0
Unexpected Pass:       0
Skipped:               0
Timeout:               0

Full log written to /tmp/something/testlog.txt
```
[testlog.txt](https://github.com/falconindy/auracle/files/3768950/testlog.txt)

**Comment by falconindy** [comment]
I'm not interested in doing this because I can't commit to actually testing it on arm. If I can setup a CI with an ARM build, I'd be fine adding this.

**Comment by solsticedhiver** [comment]
If it could help https://wiki.archlinux.org/index.php/QEMU#Chrooting_into_arm/arm64_environment_from_x86_64

One can run an arm build/install from within a x86_64 machine with a simple chroot/systemd-nspawn (even better than a VM)

**Comment by falconindy** [comment]
Sorry, but it doesn't help. I specifically need something I can run in a CI build -- I'm not going to be manually testing arm compilation.
