### ISSUE TITLE
Search by Co-Maintainer.

### ISSUE THREAD

**Issue by bartoszek** [falconindy/auracle#61]
Would it be possible to include Co-Maintainers in `--searchby` :thinking:

**Comment by falconindy** [comment]
No, it isn't. This needs to be supported by the AUR before auracle can/will support it.

**Comment by bartoszek** [comment]
A workaround involving `curl` and `hq`
#### Explanation:
- `SeB=?` search by
  - `c` co-maintainer
- `K=?` keywords
- `PP=?` results per page

```sh
$ curl -sSL 'https://aur.archlinux.org/packages/?SeB=c&PP=250&K=bartus'|hq td:first-of-type text                                        
ccache-ext
inkscape-git
luxrays-hg
luxrender-hg
openboard
openmvg-git
optix
visual-sfm
```
