### ISSUE TITLE
Split package.

### ISSUE THREAD

**Issue by bartoszek** [falconindy/auracle#62]
Would it be feasible to list `pkgbase` for split package instead of naming each one `pkgname`.

**Comment by falconindy** [comment]
Can you give me an example of the output now and the output you would like to see?

**Comment by bartoszek** [comment]
What I'm looking for query like this to output single `pkgbase` instead of two `pkgname` for the split package [seexpr-qt5](https://aur.archlinux.org/packages/seexpr-qt5)
```sh
$ auracle --searchby maintainer search bartus -F {name}|grep seexpr-qt5
seexpr-qt5
seexpr-qt5-doc
```
