### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [falconindy/auracle#63]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by Morganamilo** [comment]
Auracle doesn't even build packages...

**Comment by AladW** [comment]
I have to wonder. Did you parse the AUR Helper page on the wiki with a script, and automatically filed an issue for every package on there?

/me checks if devtools has a new issue as well 🤔

**Comment by ts1a** [comment]
> I have to wonder. Did you parse the AUR Helper page on the wiki with a script, and automatically filed an issue for every package on there?

Nope. He created all these manually. :laughing:
