### ISSUE TITLE
Handle '503 - Service Unavailable'

### ISSUE THREAD

**Issue by vyachkonovalov** [falconindy/auracle#64]
Got
> terminate called after throwing an instance of 'nlohmann::detail::parse_error'
>   what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
> Aborted (core dumped)

from
```shell
auracle sync
```
due to aur.archlinux.org on maintenance.

![AUR on maintenance](https://i.imgur.com/h6wLsky.png)

**Comment by solsticedhiver** [comment]
+1
something better and less cryptic will be appreciated

it's the same for `auracle sarch ...` or `auracle download ....`

**Comment by falconindy** [comment]
Sure, this is all the same code path. The code is meant to handle this properly, but because the AUR responds with HTML in addition to the 503, auracle ends up trying to parse the HTML as JSON.

Easily fixed...
