### ISSUE TITLE
Segfault with dependency cycle

### ISSUE THREAD

**Issue by rmarquis** [falconindy/auracle#7]
Installing the `mingw-w64-freetype2` package results in a dependency cycle, which produces a segfault instead of a nicer error message.

```
$ auracle buildorder mingw-w64-freetype2
Segmentation fault (core dumped)
```

Note the dependency cycle is `mingw-w64-freetype2 -> mingw-w64-harfbuzz -> mingw-w64-freetype2`, but isn't exacly a PKGBUILD error, as the chain is supposed to be bootstrapped with the `mingw-w64-freetype2-bootstrap` package.

**Comment by falconindy** [comment]
Ah IteratePackages doesn't seem to protect against loops.

**Comment by falconindy** [comment]
Ah no... it's the InMemoryRepo which doesn't properly protect against loops... Easily fixed.

**Comment by rmarquis** [comment]
I'd also suggest to add an error or warning message, since as it is the build chain is not buildable. Granted, this is a very edgy case.
