### ISSUE TITLE
Download command not really mentioned in documentation

### ISSUE THREAD

**Issue by JannoT** [falconindy/auracle#72]
> $ auracle -v

Has no mention of download command at all.

[README.md](https://github.com/falconindy/auracle/blob/master/README.md)
Has no mention of download command at all.

[auracle.1.pod](https://github.com/falconindy/auracle/blob/master/man/auracle.1.pod)

> -r, --recurse
    When used with the download command, recursively follow and download dependencies of each given argument.

The -r option has the only mention of the download command existing at all.

**Comment by falconindy** [comment]
Working as intended. See d59f80b1b. I'll remove the manpage reference.

**Comment by falconindy** [comment]
b5b41d70e5b8b979a9a5c86543ddec0d1a47fc57 removes mention of 'download' from the manpage. Expect the verb itself to be removed at some point in the future.
