### ISSUE TITLE
Detect cyclic dependencies

### ISSUE THREAD

**Issue by yshui** [falconindy/auracle#75]
```
▶ auracle buildorder afdko
SATISFIEDREPOS python
SATISFIEDREPOS python-lxml
SATISFIEDREPOS python-fonttools
SATISFIEDREPOS python-fs
SATISFIEDREPOS python-setuptools-scm
SATISFIEDREPOS python-pytest-cov
SATISFIEDREPOS python-pytest-xdist
SATISFIEDREPOS python-pytest-randomly
SATISFIEDAUR psautohint psautohint
SATISFIEDREPOS python-setuptools
SATISFIEDREPOS python2-setuptools
SATISFIEDREPOS cython
SATISFIEDREPOS cython2
SATISFIEDAUR python-pyclipper python-pyclipper
SATISFIEDREPOS python-pytest
SATISFIEDAUR python-defcon python-defcon
SATISFIEDREPOS python-pytest-runner
SATISFIEDAUR python-fontmath python-fontmath
SATISFIEDAUR python-fontparts python-fontparts
SATISFIEDAUR python-fontpens python-fontpens
SATISFIEDAUR python-booleanoperations python-booleanoperations
SATISFIEDREPOS python-brotli
SATISFIEDREPOS python-coverage
SATISFIEDAUR python-cu2qu python-cu2qu
SATISFIEDAUR python-mutatormath python-mutatormath
SATISFIEDAUR python-ufonormalizer python-ufonormalizer
SATISFIEDREPOS python-wheel
SATISFIEDAUR python-ufoprocessor python-ufoprocessor
SATISFIEDREPOS python-unicodedata2
SATISFIEDREPOS python-zopfli
TARGETAUR afdko afdko
```

Here python-booleanoperations is ordered after python-fontparts, but python-fontparts depends on the former (https://aur.archlinux.org/packages/python-fontparts/)

**Comment by yshui** [comment]
Looks to me `WalkDependencies` walks the dependencies depth first, while it actually should be doing a [topological sort](https://en.wikipedia.org/wiki/Topological_sorting)

**Comment by yshui** [comment]
Sorry, I was wrong earlier. Looks like there is a dependency cycle in the graph:

booleanoperations -> fontpens -> fontparts -> booleanoperations

It would be nice if auracle could report an error or warning in this case.

**Comment by yshui** [comment]
Or in this case, an option to ignore check dependecies or the user can manually resolve the dependency cycle by building without check() first.

**Comment by falconindy** [comment]
Yeah, this is a known deficiency. I haven't gotten around to writing the code to report cycles. It's been in my head, I just haven't written it down. Quickly scraping that together, I actually find another cycle (also via checkdepends):

```
$ build/auracle buildorder afdko
found cycle: python-booleanoperations -> python-fontpens -> python-fontparts -> python-booleanoperations
found cycle: python-fontpens -> python-fontparts -> python-fontpens
SATISFIEDREPOS python
SATISFIEDREPOS python-lxml
REPOS python-fonttools
REPOS python-fs
REPOS python-setuptools-scm
REPOS python-pytest-cov
REPOS python-pytest-xdist
REPOS python-pytest-randomly
AUR psautohint psautohint
SATISFIEDREPOS python-setuptools
REPOS python2-setuptools
SATISFIEDREPOS cython
REPOS cython2
AUR python-pyclipper python-pyclipper
REPOS python-pytest
AUR python-defcon python-defcon
REPOS python-pytest-runner
AUR python-fontmath python-fontmath
AUR python-fontparts python-fontparts
AUR python-fontpens python-fontpens
AUR python-booleanoperations python-booleanoperations
REPOS python-brotli
REPOS python-coverage
AUR python-cu2qu python-cu2qu
AUR python-mutatormath python-mutatormath
AUR python-ufonormalizer python-ufonormalizer
REPOS python-wheel
AUR python-ufoprocessor python-ufoprocessor
REPOS python-unicodedata2
REPOS python-zopfli
TARGETAUR afdko afdko
```

I've been thinking about the 'ignore checkdepends' thing as well, because it's come up before. I don't think I want a specific --nocheckdepends flag, or something along those lines, but a more generic flag that could let you skip certain depend kinds or override entirely. The default would be to check everything, but you could do something like: `--resolve-depends=^checkdepends` to skip checkdepends or `--resolve-depends=depends` to only resolve depends, skipping checkdepends and makedepends. I'm using ^ instead of ! (I could easily allow both) because of interactions with history, e.g.

```
$ auracle --resolve-depends=!depends afdko
-bash: !foo: event not found
```

**Comment by falconindy** [comment]
Can you take a look at my `cycles` branch? It's not 100% polished, but I'm curious what you think.

**Comment by yshui** [comment]
@falconindy I don't see any problem with that. maybe looking for cycle_start in a vector would be a bit slow? you can probably use a unordered_set to keep track of dependency path, and the cycle can be printed by returning from walk() until you hit cycle_start.

**Comment by falconindy** [comment]
Appreciate the feedback, however... Performance with a vector would scale as roughly linear with the depth of the tree and highly likely to be a single digit number of iterations. I *really* can't see this being performance-impacting, and using a hashset/unwinding sounds like it would produce far more complicated code.

**Comment by yshui** [comment]
@falconindy Yeah, I think you are right.
