### ISSUE TITLE
Compiling heat up cpu?

### ISSUE THREAD

**Issue by tmpm697** [falconindy/auracle#77]
Idk if this is the way how c++ sourcecode compiled but compare to `yay` my cpu when `makepkg -si` `yay` is 40 degress while `auracle` heat up to 53 degrees.

It does not an issue if I live in an ideal world with good thermal, but with daily use on a low level pc -- SBC, it still shows some concerns.

Is there a way to avoid this issue?

**Comment by gnubeest** [comment]
Auracle neither compiles nor builds packages, so this is not an auracle issue either way.

Regardless, I've never used yay and don't know much about how it operates, but unless it's doing something odd like using different MAKEFLAGS or package compression than what's in your makepkg.cfg (which wouldn't surprise me), you won't be seeing increased CPU temperatures solely by using makepkg without an AUR builder.

**Comment by falconindy** [comment]
This is among the stranger bug reports that I've received.
