### ISSUE TITLE
List all installed AUR packages

### ISSUE THREAD

**Issue by christarazi** [falconindy/auracle#83]
I'd like to list all installed AUR packages (not "official" packages) and their versions. Is this something that's possible or something you'd consider adding?

**Comment by polyzen** [comment]
`Use pacman -Qqem > foreignpkglist.txt to create the list of AUR and other foreign packages that have been explicitly installed.`
https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#List_of_installed_packages

**Comment by falconindy** [comment]
As polyzen mentions, this is a job for pacman, not auracle. Though, I tend to think this is a better wiki link:

https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Listing_packages

Specifcally:

> `List all foreign packages (typically manually downloaded and installed or packages removed from the repositories): pacman -Qm.`
