### ISSUE TITLE
Add pkgbase to buildorder output

### ISSUE THREAD

**Issue by rmarquis** [falconindy/auracle#9]
For reference, quick extract of our emails discussion from a few weeks ago:

>>> [...]
>>> libsystemd-git is provided by the systemd-git PKGBUILD, but it's difficult to establish this reverse mapping without a fair bit of extra machinery. Can pacaur handle this nicely, or does it need to avoid the libsystemd-git dep because it's implicitly handled by build+install of systemd-git?

>> Pacaur does that extra bit of machinery by itself [...] It does some pkgbase magic just before building to ensure a single build per pkgbase, and installation of spit packages in the correct order.

> Cool. I've already got a naive graph implementation that can walk package deps and print a build order. I'll take this extra coalescing step as a nice-to-have. Certainly seems like an optimization that could be applied later...

Getting the pkgbase list is useful, f.e. to:
* easily get the path of sources files in order to review them
* obtain the packages to download, so `git clone` can be used instead of `auracle download`
* handle split packages build

I initially thought I would use the upcoming custom output to retrieve the list of pkgbase (with `auracle info --format %b` or similar), but I realize now that obtaining the pkgbase list directly through `buildorder` might be a wiser generic implementation. In fact, I am not sure when the pkgname list alone can be useful without also getting the related pkgbase list (maybe apart from inspecting a build chain).

Having an extra column that outputs pkgbase directly is straighforward to implement and would also avoid to use an extra RPC request.

```
$ ./auracle buildorder systemd-git
BUILD libsystemd-git systemd-git
BUILD systemd-git systemd-git
```

Drawback is that the output is not so nice to look at anymore, and I am also not sure how this fit with the optimization you were referring to. Opinion?

**Comment by falconindy** [comment]
Alternate output style: pkgbase first, followed by each of the pkgnames it provides, e.g.

```
BUILD systemd-git 
```

**Comment by rmarquis** [comment]
That wouldn't really work, since in that case the information of topologically sorted dependencies between split packages would be lost.

As a reminder, all subpackages of a split package are built, but they are not necessarily all installed (this defeat the point of split packages, and there are even valid cases where subpackages conflict between themselves).

I can however imagine something similar to the following:
```
BUILD systemd-git systemd-git libsystemd-git
```
with only the required dependencies listed, and with the print order of these split dependency sorted accordingly. This sounds however like more complexity in both auracle and wrappers for little benefit imho.

Alternative possibility: keep current default output as it is, and add another optional flag to output both pkgbase and pkgname.

**Comment by rmarquis** [comment]
Suggestion from @AladW on IRC:

Use something like
```
buildorder --format '%foo'
```

which sounds like an excellent solution to me.

**Comment by AladW** [comment]
An example of how this could be used:

https://paste.xinu.at/p3PTc

A command line using cower formatters and `%U` for `URLPath` could look as:
```
auracle buildorder --format '%n %b %v %U' | column -t
```
