### ISSUE TITLE
List all aur packages

### ISSUE THREAD

**Issue by zijian-x** [falconindy/auracle#91]
I'd like to make a zsh function to use fzf to search for packages and need to list all the packages available as the base. Is it possible in any way? I tried to use regex search with ".*" but it did not work as intended.

**Comment by Zyanite7** [comment]
Right now I could use aurutils `($ aur pkglist)` for that but I'd still want to keep only one helper for all.

**Comment by falconindy** [comment]
The AUR provides a regularly updated package list that you can use for this purpose:

https://aur.archlinux.org/packages.gz

Caching this file in auracle is probably out of scope.
