### ISSUE TITLE
Check -git package outdate?

### ISSUE THREAD

**Issue by tmpm697** [falconindy/auracle#96]
Can you add this to `auracle`?

**Comment by ThePirate42** [comment]
No they can't, the aur doesn't keep version information about git packages, it is calculated on the fly.

**Comment by ThePirate42** [comment]
But in that case auracle should already be able to detect it, right?

**Comment by rellieberman** [comment]
If the pkgrel has been bumped, auracle should report an update

**Comment by ThePirate42** [comment]
Exactly, I think we are saying the same thing.

**Comment by rellieberman** [comment]
I mean that if pkgrel is updated in the PKGBUILD, then auracle would pick it up

**Comment by polyzen** [comment]
> Correct me if I'm wrong, but if a critical update exists in a -git package the maintainer would generally bump the pkgrel, so the update is seen by the users.

The maintainer would build the update locally, thereby bumping the `pkgver`, and could then commit and push that.

**Comment by tmpm697** [comment]
`-git` packages not often change `pkgrel` for its git update.

**Comment by tmpm697** [comment]
This is the only reason hold me back from use `auracle` totally for `aur` packages. I currently use `paru` to track `-git` packages and `auracle` as a backup.

**Comment by tmpm697** [comment]
I want to know if there's new commit to the repo, so I can decide to update it manually via makepkg or not.

**Comment by polyzen** [comment]
You could track their feeds, eg. https://github.com/falconindy/auracle/commits/master.atom.

**Comment by tmpm697** [comment]
No, I want `auracle` to keep track of all `aur` packages that ended with `-git` when there's new commit to the repo that `-git` packages based from.

**Comment by falconindy** [comment]
auracle is probably never going to do this. Auracle is focused on consuming what's made available by the AUR's RPC interface, and I don't have much interest in randomly querying git repos.
